USE PROJECT

--1.Create STUDENT_INFO table with following columns

CREATE TABLE STUDENT_INFO (
year char(4) not null check(len(year)=4),
sequenceno int identity (1,1),
STUDENT_ID as ('STD_'+ year+'_'+right('00'+cast(sequenceno as varchar(2)),2)) persisted Primary key,
NAME varchar(20) not null,
ADDRESS varchar(20) not null,
PHONE_NO Bigint Not null check(len(PHONE_NO) = 10 and left(PHONE_NO ,1)>0) ,
EMAIL_ID VARCHAR(30) NOT NULL CHECK (EMAIL_ID LIKE '%_[@]_%' ) ,
QUALIFICATION1 VARCHAR(50),
QUALIFICATION2 VARCHAR(50),
EXPERIENCE FLOAT NOT NULL ,
COMPANY_NAME VARCHAR(50),
COURSE_OPTED1 VARCHAR(50) NOT NULL CHECK(COURSE_OPTED1 IN('REPORTING ANALYSIS POWER PACK',
'BUSINESS ANALYTICS POWER PACK',
'DATA ANALYTICS POWER PACK',
'DATA SCIENCE MODELLING & MACHINE LEARNING')),
COURSE_OPTED2 VARCHAR(50) CHECK(COURSE_OPTED2 IN('REPORTING ANALYSIS POWER PACK',
'BUSINESS ANALYTICS POWER PACK',
'DATA ANALYTICS POWER PACK',
'DATA SCIENCE MODELLING & MACHINE LEARNING')),
COURSE_OPTED3 VARCHAR(50) CHECK(COURSE_OPTED3 IN('REPORTING ANALYSIS POWER PACK',
'BUSINESS ANALYTICS POWER PACK',
'DATA ANALYTICS POWER PACK',
'DATA SCIENCE MODELLING & MACHINE LEARNING')),
ADMISSION_DATE DATE NOT NULL,
EXPECTED_END_DATE AS CASE
WHEN COURSE_OPTED1 = 'REPORTING ANALYSIS POWER PACK' THEN DATEADD(MONTH,3,ADMISSION_DATE)
WHEN COURSE_OPTED1 = 'BUSINESS ANALYTICS POWER PACK'THEN DATEADD(MONTH,6,ADMISSION_DATE)
WHEN COURSE_OPTED1 = 'DATA ANALYTICS POWER PACK' THEN DATEADD(MONTH,7,ADMISSION_DATE)
WHEN COURSE_OPTED1 = 'DATA SCIENCE MODELLING & MACHINE LEARNING' THEN DATEADD(MONTH,8,ADMISSION_DATE)
END)



INSERT INTO STUDENT_INFO(year,
NAME,
ADDRESS,
PHONE_NO,
EMAIL_ID,
QUALIFICATION1,
EXPERIENCE,
COURSE_OPTED1,
ADMISSION_DATE
)select '2024','Amit','Aaaa ss 12c d','8234456789','aaaa@fgvff.com','MBA',4.5,'DATA SCIENCE MODELLING & MACHINE LEARNING','01-06-2024'

INSERT INTO STUDENT_INFO(year,
NAME,
ADDRESS,
PHONE_NO,
EMAIL_ID,
QUALIFICATION1,
EXPERIENCE,
COURSE_OPTED1,
ADMISSION_DATE
)select '2022','Ram','Abb Ao 12m d','1234567810','abb@fgvff.com','B. tech',1,'BUSINESS ANALYTICS POWER PACK','06-3-2023'


SELECT *
FROM STUDENT_INFO

--2.Create R_marks_info table with following columns
 CREATE TABLE R_MARKS_INFO(
 STUDENT_ID VARCHAR(11) NOT NULL FOREIGN KEY REFERENCES  STUDENT_INFO(STUDENT_ID),
 CLASS_START_DATE DATE,
 CLASS_END_DATE DATE,
 FACULTY VARCHAR(50) NOT NULL,
 TEST_1 INT ,
 TEST_2 INT ,
 TEST_3 INT,
 RETEST_1 INT,
 RETEST_2 INT,
 RETEST_3 INT)


 SELECT *
 FROM R_MARKS_INFO

 --3.Create SAS_marks_info table with following columns
CREATE TABLE SAS_MARKS_INFO(
STUDENT_ID VARCHAR(11) NOT NULL FOREIGN KEY REFERENCES  STUDENT_INFO(STUDENT_ID),
CLASS_START_DATE DATE,
CLASS_END_DATE DATE,
FACULTY VARCHAR(20),
MT1 INT,
MT2 INT,
DATA_STEP_TEST INT,
MT3 INT,
PROC_TEST INT,
BASE_SAS_TEST INT,
RETEST_1 INT,
RETEST_2 INT,
RETEST_3 INT)

SELECT * FROM SAS_MARKS_INFO

--4. Create SQL_marks_info table with following columns
CREATE TABLE SQL_MARKS_INFO(
 STUDENT_ID VARCHAR(11) NOT NULL FOREIGN KEY REFERENCES  STUDENT_INFO(STUDENT_ID),
 CLASS_START_DATE DATE,
 CLASS_END_DATE DATE,
 FACULTY VARCHAR(50) NOT NULL,
 SQL_TEST1 INT ,
 SQL_TEST2 INT ,
 RETEST1 INT,
 RETEST2 INT,
 )

 SELECT * FROM SQL_MARKS_INFO

--5. Create EXCEL_marks_info table with following columnS
CREATE TABLE EXCEL_MARKS_INFO(
 STUDENT_ID VARCHAR(11) NOT NULL FOREIGN KEY REFERENCES  STUDENT_INFO(STUDENT_ID),
 CLASS_START_DATE DATE,
 CLASS_END_DATE DATE,
 FACULTY VARCHAR(50) NOT NULL,
 BASIC_EXCEL_TEST INT,
 MT1 INT,
 EXCEL_TEST1 INT,
 RETEST INT)

 --6. Create VBA_marks_info table with following columns
 CREATE TABLE VBA_MARKS_INFO(
 STUDENT_ID VARCHAR(11) NOT NULL FOREIGN KEY REFERENCES  STUDENT_INFO(STUDENT_ID),
 CLASS_START_DATE DATE,
 CLASS_END_DATE DATE,
 FACULTY VARCHAR(50) NOT NULL,
 FUNCTION_EXCEL_TEST INT,
 FUNCTION_VBA_TEST INT,
 FINAL_TEST INT,
 RETEST1 INT)

 --7. Create TABLEAU_marks_info table with following columns
 CREATE TABLE TABLEAU_MARKS_INFO(
 STUDENT_ID VARCHAR(11) NOT NULL FOREIGN KEY REFERENCES  STUDENT_INFO(STUDENT_ID),
 CLASS_START_DATE DATE,
 CLASS_END_DATE DATE,
 FACULTY VARCHAR(50) NOT NULL,
 MT1 INT,
 TEST1 INT,
 RETEST1 INT)

 --8. Create PYTHON_marks_info table with following columns
 CREATE TABLE PYTHON_MARKS_INFO(
 STUDENT_ID VARCHAR(11) NOT NULL FOREIGN KEY REFERENCES  STUDENT_INFO(STUDENT_ID),
 CLASS_START_DATE DATE,
 CLASS_END_DATE DATE,
 TEST1 INT,
 TEST2 INT,
 RETEST1 INT,
 RETEST2 INT)

 --9. Create ASAS_marks_info table with following columns
 CREATE TABLE ASAS_MARKS_INFO(
 STUDENT_ID VARCHAR(11) NOT NULL FOREIGN KEY REFERENCES  STUDENT_INFO(STUDENT_ID),
 CLASS_START_DATE DATE,
 CLASS_END_DATE DATE,
 FACULTY VARCHAR(50) NOT NULL,
 MT1 INT,
 MT2 INT,
 FINAL_TEST1 INT,
 RETEST2 INT)

 --10.Create FULL_LENGTH_marks_info table with following columns
 CREATE TABLE FULL_LENGTH_MARKS(
 STUDENT_ID VARCHAR(11) NOT NULL FOREIGN KEY REFERENCES  STUDENT_INFO(STUDENT_ID),
 CLASS_START_DATE DATE,
 CLASS_END_DATE DATE,
 FACULTY VARCHAR(50) NOT NULL,
 R_TEST INT,
 SAS_TEST INT,
 SQL_TEST INT,
 EXCEL_TEST INT,
 VBA_TEST INT,
 PYTHON_TEST INT,
 TABLEAU_TEST INT)

--11.Create Placement_Activity table with following columnS
CREATE TABLE PLACEMENT_ACTIVITY(
STUDENT_ID VARCHAR(11) NOT NULL FOREIGN KEY REFERENCES  STUDENT_INFO(STUDENT_ID),
MOCK_INTERVIEW1 VARCHAR(50),
MOCK_INTERVIEW2 VARCHAR(50),
MOCK_INTERVIEW3 VARCHAR(50),
RESUME_FINALISED VARCHAR(50),
PROFILE_BUILDING VARCHAR(50),
CERTIFICATE_ISSUED CHAR(10) NOT NULL CHECK(CERTIFICATE_ISSUED IN('YES','NO')),
ACTUAL_COURSE_END_DATE DATE )



